### ISSUE TITLE
Crash when self CA handling

### ISSUE THREAD

**Issue by Pitenager** [0xInfection/XSRFProbe#36] opened 2019-11-21 11:15 UTC
Hi, 

I'm trying to test my webapp in the dev environment (with a self signed certificate) and I get the following crash:

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib/python3.6/http/client.py", line 1254, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1300, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1249, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 974, in send
    self.connect()
  File "/usr/lib/python3.6/http/client.py", line 1415, in connect
    server_hostname=server_hostname)
  File "/usr/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib/python3.6/ssl.py", line 817, in __init__
    self.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 1077, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/xsrfprobe", line 4, in <module>
    __import__('pkg_resources').run_script('xsrfprobe==2.1.1', 'xsrfprobe')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1445, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.6/dist-packages/xsrfprobe-2.1.1-py3.6.egg/EGG-INFO/scripts/xsrfprobe", line 15, in <module>
  File "/usr/local/lib/python3.6/dist-packages/xsrfprobe-2.1.1-py3.6.egg/xsrfprobe/xsrfprobe.py", line 14, in startEngine
  File "/usr/local/lib/python3.6/dist-packages/xsrfprobe-2.1.1-py3.6.egg/xsrfprobe/core/main.py", line 86, in Engine
  File "/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)>
```

Thank you for your hard work.
Best wishes.

**Comment by 0xInfection** [comment] 2019-11-23 13:13
The only way I see this getting resolved is by adding another switch, something probably `--no-verify` which will not verify the SSL certificates on requests during that session.

**Comment by Pitenager** [comment] 2019-11-23 16:39
Sounds well.
Are you going to work on it or should I make a PR ?

Thanks dude.

**Comment by 0xInfection** [comment] 2019-11-24 01:55
I have already started working on it. Keep an eye out on the [`ca-fix`](https://github.com/0xInfection/XSRFProbe/tree/ca-fix) branch for updates. __:__)

**Comment by 0xInfection** [comment] 2019-11-24 01:55
I have already started working on it. Keep an eye out on the [`ca-fix`](https://github.com/0xInfection/XSRFProbe/tree/ca-fix) branch for updates. __:__)

**Comment by 0xInfection** [comment] 2019-11-25 13:39
Hi @Pitenager, would you please try out the [`ca-fix`](https://github.com/0xInfection/XSRFProbe/tree/ca-fix) fix and test out the code before I publish a new release?

**Comment by Pitenager** [comment] 2019-11-25 17:26
HI @0xInfection,

It still crashes.
I'm launching the tool the following way: 
```
xsrfprobe -u https://xxxx.yyyy.zzz.com/vvv/ -c "user=cookieValue1,_ga=cookieValue2,server_id=cookieValue3,_gid=cookieValue4" --no-verify
```

And this is the output:
```
 [!] Testing site xxxx.com status...
 [+] Site seems to be up!
 [!] Testing vvvv/ endpoint status...
 [-] Connection Aborted: xxxx.com
```

I think that there is a bug parsing the url because my full url is something like:
```
https://xxxx-yyyy.zzzz.wwww.com
```

And the tool tries to connect to wwww.com.

It seems like the parser only gets the .com and the previous part.

I also create an environment var to try to bypass the SSL checking:
```
export REQUESTS_CA_BUNDLE=/home/testLab/Desktop/LabsteamCA.crt
```

But I still think that the url parsing could be the root of the problem.

Cheers!

**Comment by 0xInfection** [comment] 2019-11-27 05:10
Okay. I'm probing into the problem rn. :)

**Comment by 0xInfection** [comment] 2019-11-28 08:55
Hi @Pitenager, the final set of changes should work as expected. :)

**Comment by Pitenager** [comment] 2019-12-02 17:52
Sorry dude, I was far from home these days.
Tomorrow I'll check the changes.

**Comment by Pitenager** [comment] 2019-12-11 10:16
Hi @0xInfection 

Sorry for the delay. I'm still having the same issue. 
Here is the output: 

![Selección_028](https://user-images.githubusercontent.com/32803812/70612685-ab268a80-1c07-11ea-9cdc-2785ba655082.png)

Edit1: I can access the endpoint via browser.

**Comment by 0xInfection** [comment] 2019-12-11 13:10
Hi @Pitenager, I probably think that it is your server which is somehow not accepting connections. Maybe providing a bit of information about your server setup might help. 

You can also try changing the default headers within xsrfprobe by copying the request headers from your browser to the `config.py` file. Do read the [wiki](https://github.com/0xInfection/XSRFProbe/wiki/FAQs#what-if-i-want-my-own-custom-headers-while-making-requests) on this. Lmk if that works out.

**Comment by Pitenager** [comment] 2019-12-11 13:43
Hi again @0xInfection, 

I tested that way by changing the headers but it did not make sense. 
I think it is not problem of the server because other tools can connect and make their stuff and my own tools, just by adding the `verify=False` works fine.

Any other idea ? I don't know any other approach.

Thank you.

**Comment by 0xInfection** [comment] 2019-12-16 18:53
Hi @Pitenager, 

I debugged the issue and found the problem was not at all the root of the problem. The `--no-verify` flag actually does set the `verify=False` to the requests for that session. Please reviw the set of request headers which XSRFProbe is sending by the `--display` flag.

Since you said that all other tools worked when you just did the `verify=False` manually, you can easily try changing the following two lines within the `request.py` file, and see if it work out for you: 
1. https://github.com/0xInfection/XSRFProbe/blob/09266a6473557114a4d99506fdd177995bf02ebd/xsrfprobe/core/request.py#L47-L48
2. https://github.com/0xInfection/XSRFProbe/blob/09266a6473557114a4d99506fdd177995bf02ebd/xsrfprobe/core/request.py#L92-L93

Also please do check [this stackoverflow question](https://stackoverflow.com/questions/28557466/python-requests-exception-connectionerror-connection-aborted-badstatusline) out.  
As, I cannot reproduce the above said error, I'll probably have to close this issue as non-reproducible. Thank you again for pulling this issue up. Have a merry Christmas ahead.

Cheers!

**Closed as completed by 0xInfection** 2019-12-16 18:53 UTC
Labels: enhancement, featured, feature request
